# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-21 02:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0002_auto_20160619_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
