# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-21 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0005_auto_20160621_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
