# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-22 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0010_auto_20160622_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='option',
            field=models.CharField(choices=[('c', 'career'), ('r', 'relationship'), ('e', 'education'), ('o', 'other')], max_length=10, null=True),
        ),
    ]
