# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-22 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0011_post_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='option',
            field=models.CharField(choices=[('c', 'career'), ('relation', 'relationship'), ('e', 'education'), ('o', 'other')], max_length=10, null=True),
        ),
    ]
