# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-22 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0012_auto_20160622_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='option',
            field=models.CharField(choices=[('career', 'career'), ('relationship', 'relationship'), ('education', 'education'), ('other', 'other')], max_length=10, null=True),
        ),
    ]
