# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-07 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0015_auto_20160627_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='notifications1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('writer', models.CharField(max_length=120, null=True)),
                ('message_id', models.PositiveIntegerField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('creator', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
