# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-08 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0017_notifications1_boolean_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
