# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-08 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0018_post_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
