# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-11 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0022_remove_post_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='option',
            field=models.CharField(choices=[('career', 'career'), ('relationship', 'relationship'), ('education', 'education'), ('other', 'other')], max_length=20, null=True),
        ),
    ]
