# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-29 04:29
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20160628_2255'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
