# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-06 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0005_notifications_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='writer',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
