# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-06 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0006_auto_20160706_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
