# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-06 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0007_auto_20160707_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='creator',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
