# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-07 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0008_notifications_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='boolean_field',
            field=models.BooleanField(default=False),
        ),
    ]
